---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: submariner-0-23-1-stage-20260319-01
  namespace: submariner-tenant
  labels:
    release.appstudio.openshift.io/author: 'dfarrell07'
spec:
  releasePlan: submariner-release-plan-stage-0-23
  snapshot: submariner-0-23-20260319-210011-000
  data:
    releaseNotes:
      type: RHBA  # Change to RHSA if adding CVEs, RHEA for enhancements
      issues:
        fixed: []  # Fill with Step 9 workflow
      cves: []     # Fill with Step 9 workflow (required if type=RHSA)
