---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: submariner-0-24-0-prod-20260526-01
  namespace: submariner-tenant
  labels:
    release.appstudio.openshift.io/author: 'dfarrell07'
spec:
  releasePlan: submariner-release-plan-prod-0-24
  snapshot: submariner-0-24-20260512-181004-000
  data:
    releaseNotes:
      type: RHBA
      issues:
        fixed:
          - id: ACM-32309
            source: issues.redhat.com
