---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: submariner-fbc-4-20-stage-20251204-01
  namespace: submariner-tenant
  labels:
    release.appstudio.openshift.io/author: 'dfarrell07'
spec:
  releasePlan: submariner-fbc-release-plan-stage-4-20
  snapshot: submariner-fbc-4-20-hr5t6
