---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: submariner-fbc-4-17-prod-20260414-01
  namespace: submariner-tenant
  labels:
    release.appstudio.openshift.io/author: 'dfarrell07'
spec:
  releasePlan: submariner-fbc-release-plan-prod-4-17
  snapshot: submariner-fbc-4-17-20260413-173041-000
