---
name: Validate Releases

'on':
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          set -euo pipefail
          url=https://github.com/mikefarah/yq/releases/latest/download
          sudo wget -qO /usr/bin/yq ${url}/yq_linux_amd64
          sudo chmod +x /usr/bin/yq

      - name: Install Python tools
        run: pip install gitlint yamllint

      - name: Run unit tests
        run: make test
